services:
  inventory.api:
    image: inventory.api
    ports:
      - "57000:80"
      - "57100:443"
    build:
      context: .
      dockerfile: Inventory.Api/Dockerfile

  eventbus:
    image: rabbitmq:3-management
    container_name: inventory-eventbus
    ports:
      - 5672:5672
      - 15672:15672

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: inventory-sql
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "2u3866ppTpazDLzyEiIw"